module.exports = {
    userFormateError: {
        code:'10001',
        message:'用户名或者密码不能为空',
        result:''
    },
    userAlreadyExisted: {
        code:'10002',
        message:'用户已经存在',
        result:''
    },
    registerError:{
        code:'10003',
        message:'用户注册错误',
        result:''
    },
    userDoesNotExist:{
        code:'10004',
        message:'用户不存在',
        result:''
    },
    userLoginError:{
        code:'10005',
        message:'用户登录错误',
        result:''
    },
    passwordError:{
        code:'10006',
        message:'密码输入错误',
        result:''
    },
    LoginError:{
        code:'10007',
        message:'用户登录错误',
        result:''
    },
    tokenExpiredError:{
        code:'10101',
        message:'token过期',
        result:''
    },
    invalidTokenError:{
        code:'10102',
        message:'无效的token信息',
        result:''
    },
    changePasswordError:{
        code:'10103',
        message:'密码修改失败',
        result:''
    },
    getAllPlansError:{
        code:'10201',
        message:'获取所有计划失败',
        result:''
    },
    addPlansError:{
        code:'10202',
        message:'添加计划失败',
        result:''
    }

}